module.exports = [
    {
        "id":"0",
        "name":"Myer",
        "addr":"Melbourne",
        "tag":
        [
            "clothing",
            "toilet",
        ]
    },
    {
        "id":"1",
        "name":"McDonalds",
        "addr":"example1",
        "tag":
        [
            "food",
            "toilet",
        ]
    },
    {
        "id":"2",
        "name":"Louis Vuitton",
        "addr":"Chadstone",
        "tag":
        [
            "clothing",
        ]
    },
    {
        "id":"3",
        "name":"7-Eleven",
        "addr":"Carlton",
        "tag":
        [
            "petrol",
            "food",
            "toilet",
        ]
    },
];